### ISSUE TITLE
火绒6.0，自定义规则导入后不显示，自动操作导入后会导致火绒卡死无法杀掉

### ISSUE THREAD

**Issue by mushrolling** [Linzh7/Huorong-HIPS#6]
已给STAR，初步判断可能是版本间JSON格式不同导致，版主考不考虑帮广大群众在火绒6.0下重新导出一份JSON，感激不尽

**Comment by Linzh7** [comment]
感谢反馈，已整理 用戶 @guoqidemengxin 的 PR #2 #3 #4 #5 . 作为社区贡献内容，我未对其内容进行检查，请使用前检查。
若有更多疑问，请 reopen 本 issue。

**Comment by guoqidemengxin** [comment]
您好，由于这些代码来自于火绒安全社区，我也无法审查其安全性，为了保证项目安全，我关闭了PR。只有帮助文档被合并了

**Comment by guoqidemengxin** [comment]
![Screenshot_20240830_232939](https://github.com/user-attachments/assets/9d8987d3-01cb-4f98-b0b7-1b99edf4156d)
从这张图片上各位可以直接看到我主动关闭了PR，还没有合并！

**Comment by guoqidemengxin** [comment]
或者说我无法理解，我已经关闭了这个PR，那么我这个改动就不会影响到仓库，难道我关闭请求也会影响到仓库？我很少用Github，不太理解。

**Comment by guoqidemengxin** [comment]
@Linzh7 稍后我重新写一份帮助文档，火绒6.0界面又变了，现在导入自定义规则隐藏的比较深

**Comment by guoqidemengxin** [comment]
安全领域我还是不太懂，我还是维护readme跟随火绒更新版本，做新的安装教程，感谢大佬指教。

**Comment by guoqidemengxin** [comment]
给各位造成不便，非常抱歉。

**Comment by guoqidemengxin** [comment]
我觉得这个项目维护下棋还是比较困难的，火绒社区的规则也是鱼龙混杂的

**Comment by guoqidemengxin** [comment]
不好意思，我重新阅读了一下仓库，发现已经有人帮我手动合并，不好意思。
